### ISSUE TITLE
重新编译时出现错误

### ISSUE THREAD

**Issue by TianZonglin** [takayama-lily/vscode-qq#19]
```
tzloop@tzloop-Z390:~/vscode-qq$ clear
tzloop@tzloop-Z390:~/vscode-qq$ npm i
npm WARN npm npm does not support Node.js v13.0.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11, 12.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 263 packages in 1.151s
found 0 vulnerabilities


tzloop@tzloop-Z390:~/vscode-qq$ sudo npm i typescript -g
[sudo] tzloop 的密码： 
npm WARN npm npm does not support Node.js v13.0.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11, 12.
npm WARN npm You can find the latest version at https://nodejs.org/
/usr/local/bin/tsc -> /usr/local/lib/node_modules/typescript/bin/tsc
/usr/local/bin/tsserver -> /usr/local/lib/node_modules/typescript/bin/tsserver
+ typescript@4.3.5
updated 1 package in 0.636s


tzloop@tzloop-Z390:~/vscode-qq$ sudo npm i vsce -g
npm WARN npm npm does not support Node.js v13.0.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11, 12.
npm WARN npm You can find the latest version at https://nodejs.org/
/usr/local/bin/vsce -> /usr/local/lib/node_modules/vsce/out/vsce
+ vsce@1.95.0
updated 1 package in 1.816s


tzloop@tzloop-Z390:~/vscode-qq$ sudo vsce package
internal/modules/cjs/loader.js:458
  throw e;
  ^

Error: Package exports for '/usr/local/lib/node_modules/vsce/node_modules/underscore' do not define a valid '.' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:455:13)
    at resolveExports (internal/modules/cjs/loader.js:388:16)
    at Function.Module._findPath (internal/modules/cjs/loader.js:487:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:782:27)
    at Function.Module._load (internal/modules/cjs/loader.js:688:27)
    at Module.require (internal/modules/cjs/loader.js:850:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/vsce/node_modules/typed-rest-client/handlers/ntlm.js:7:11)
    at Module._compile (internal/modules/cjs/loader.js:958:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:994:10) {
  code: 'MODULE_NOT_FOUND'
}
tzloop@tzloop-Z390:~/vscode-qq$ 
tzloop@tzloop-Z390:~/vscode-qq$ 

```

**Comment by takayama-lily** [comment]
可能是node版本太低
